| ID | Link | Pub Date | Short Summary | Include? | Inclusion Reasoning | Key Insights & Revelations |
|----|------|----------|---------------|----------|---------------------|----------------------------|
| 1 | [can-a-court-make-a-journalist-reveal...](https://transparencyproject.org.uk/can-a-court-make-a-journalist-reveal-their-source-of-information-about-a-family-court-hearing/) | 2025-06-17 | High Court reaffirms source protection. | **Y** | Core reporter right. | • **Source protection upheld** under s.10 Contempt of Court Act<br>• Court cannot compel disclosure unless *strictly necessary*<br>• **Journalists = public watchdog** in family courts<br>• **Keywords**: source anonymity, public interest, contempt risk |
| **2** | **[family-court-reporting-watch-roundup-may-2025](https://transparencyproject.org.uk/family-court-reporting-watch-roundup-may-2025/)** | **2025-05-30** | May roundup: 5 judgments, 2 with transparency orders | **Y** | Trend data: early transparency order use | • Only **5 published judgments** in May — **low volume** despite PD12R<br>• **2/5 used transparency orders** — **slow adoption**<br>• First signs of **judicial caution** in naming<br>• **Keywords**: publication rate, transparency order uptake, judicial discretion |
| 3 | [child-protection-and-domestic-abuse...](https://transparencyproject.org.uk/child-protection-and-domestic-abuse-a-legal-blogging-report-from-cardiff-family-court/) | 2025-05-27 | Cardiff care case with DA. | **N** | Single case; no trend. | — |
| 4 | [can-secret-recordings-be-used...](https://transparencyproject.org.uk/can-secret-recordings-be-used-as-evidence-in-court/) | 2025-05-22 | Admissibility of secret recordings. | **Y** | Practical evidential rule. | • **Secret recordings admissible** if *relevant and fair*<br>• **Privacy vs. truth** balancing act<br>• **No blanket ban** — case-by-case<br>• **Keywords**: covert recording, evidence, fairness, privacy breach |
| 5 | [cross-examination-of-medical-experts...](https://transparencyproject.org.uk/cross-examination-of-medical-experts-exceptional-or-exceptionally-important/) | 2025-05-18 | When to allow expert cross-exam. | **N** | Procedural; not transparency. | — |
| **6** | **[family-court-reporting-watch-roundup-april-2025](https://transparencyproject.org.uk/family-court-reporting-watch-roundup-april-2025/)** | **2025-04-25** | April: 4 judgments, first PD12R applications | **Y** | Early PD12R impact | • **First month under PD12R**: only **4 judgments** published<br>• **First transparency order applications** recorded<br>• **Baseline for measuring change**<br>• **Keywords**: PD12R launch, pilot transition, reporting pilot |
| 7 | [assisted-dying...](https://transparencyproject.org.uk/assisted-dying-what-role-for-the-panel-thoughts-on-the-latest-amended-proposals/) | 2025-05-03 | Assisted dying panels. | **N** | Off-topic. | — |
| 8 | [happy-tenth-birthday...](https://transparencyproject.org.uk/happy-tenth-birthday-to-tp/) | 2025-01-10 | TP anniversary. | **N** | Internal. | — |
| 9 | [completing-care-proceedings...](https://transparencyproject.org.uk/completing-care-proceedings-in-less-than-26-weeks/) | 2025-04-25 | 26-week target case. | **N** | Case-specific. | — |
| 10 | [abbasi-supreme-court...](https://transparencyproject.org.uk/abbasi-the-supreme-court-finally-hands-down-judgment-on-appeal-about-injunctions-made-to-protect-the-identity-of-hospital-staff-providing-end-of-life-care/) | 2025-05-02 | End-of-life staff anonymity. | **N** | Not family court. | — |
| 11 | [exhumation...](https://transparencyproject.org.uk/exhumation-where-fathers-coercive-control-undermined-decision-on-place-of-burial/) | 2025-04-15 | Exhumation + coercive control. | **N** | One-off. | — |
| 12 | [intermediaries-appeal...](https://transparencyproject.org.uk/the-intermediaries-appeal-what-does-it-tell-us/) | 2025-04-17 | Intermediaries fairness. | **N** | Fair trial. | — |
| 13 | [transparency-orders-but-can-a-parent...](https://transparencyproject.org.uk/transparency-orders-but-can-a-parent-tell-their-own-story/) | 2025-05-12 | Parental speech under transparency orders. | **Y** | Core speech right. | • **Parents can speak** — but **only within transparency order limits**<br>• **Risk of contempt** if order breached<br>• **Tension**: open justice vs. child privacy<br>• **Keywords**: parental voice, contempt risk, transparency order breach |
| 14 | [section-12-yet-more-confusion](https://transparencyproject.org.uk/section-12-yet-more-confusion/) | 2025-04-10 | s.12 AJA 1960 explainer. | **Y** | Foundational law. | • **s.12 = automatic confidentiality** in family hearings<br>• **Reporting allowed only if not from court**<br>• **Myth-busting**: “in open court” ≠ reportable<br>• **Keywords**: s.12 AJA, automatic reporting restriction, jigsaw identification |
| 15 | [transparency-orders-tool-or-straight-jacket](https://transparencyproject.org.uk/transparency-orders-tool-or-straight-jacket/) | 2025-04-23 | Transparency orders: tool or cage? | **Y** | Practical critique. | • **Transparency orders = double-edged**: enable reporting **but control it**<br>• **Judges vary** in scope and clarity<br>• **Parents feel gagged** despite “openness”<br>• **Keywords**: straight-jacket, judicial variation, parental frustration |
| 16 | [pathfinder-pilot...](https://transparencyproject.org.uk/evaluation-of-the-pathfinder-pilot-in-private-law-published/) | 2025-04-29 | Pathfinder evaluation. | **N** | Policy; not reporting. | — |
| 17 | [young-people-dol...](https://transparencyproject.org.uk/are-young-people-losing-their-freedom-because-of-deprivation-of-liberty-orders/) | 2025-05-04 | DoL orders. | **N** | Liberty issue. | — |
| **18** | **[family-court-reporting-watch-roundup-february-march-2025](https://transparencyproject.org.uk/family-court-reporting-watch-roundup-february-march-2025/)** | **2025-05-01** | Feb–Mar: 7 judgments, rise in legal blogging | **Y** | Trend: legal blogging emerging | • **7 judgments** over 2 months — **slow start**<br>• **Legal blogging increases** — new transparency vector<br>• **First multi-judge publications**<br>• **Keywords**: legal blogging, publication volume, judicial engagement |
| 19 | [access-to-family-court-documents...](https://transparencyproject.org.uk/access-to-family-court-documents-under-the-open-justice-principle/) | 2025-05-16 | Reporter document access. | **Y** | Open justice rule. | • **Reporters can request docs** under open justice<br>• **No need to attend** if already accredited<br>• **Judge discretion** — not automatic<br>• **Keywords**: document access, open justice, reporter accreditation |
| 20 | [court-of-appeal-intermediaries...](https://transparencyproject.org.uk/court-of-appeal-to-decide-on-necessity-for-intermediaries/) | 2025-05-08 | CoA intermediaries preview. | **N** | Preview. | — |
| 21 | [does-a-reporter-have-to-be-in-court...](https://transparencyproject.org.uk/does-a-reporter-have-to-be-in-court-to-read-confidential-documents/) | 2025-05-06 | Must reporters attend? | **Y** | Access rule. | • **No — remote access possible** under PD12R<br>• **Accredited reporters** can read docs without presence<br>• **Practical shift** in transparency<br>• **Keywords**: remote access, accredited reporter, PD12R flexibility |
| 22 | [transparency-board-consultation...](https://transparencyproject.org.uk/the-transparency-and-open-justice-board-consultation-on-key-objectives/) | 2025-04-28 | TP consultation response. | **Y** | Policy shaping. | • TP pushes for **listing transparency**, **judge naming**, **data dashboard**<br>• **Open justice = public trust**<br>• **Keywords**: Transparency Board, consultation, data policy |
| 23 | [guidance-on-citation...](https://transparencyproject.org.uk/guidance-on-citation-of-judgments-as-authorities/) | 2025-04-22 | Citing judgments. | **Y** | Official protocol. | • **New citation rules**: [2025] EWFC XX (B)<br>• **Encourages consistency** in reporting<br>• **Keywords**: neutral citation, authority, publication standard |
| 24 | [re-xy-twins...](https://transparencyproject.org.uk/re-xy-twins-another-family-court-judgment-names-an-individual-to-warn-parents/) | 2025-05-09 | Warning judgment. | **N** | Public interest naming. | — |
| 25 | [sperm-donor-warning...](https://transparencyproject.org.uk/judgment-published-to-warn-women-against-sperm-donor-who-has-180-kids/) | 2025-01-30 | Sperm donor warning. | **N** | Warning. | — |
| **26** | **[family-court-reporting-watch-roundup-january-2025](https://transparencyproject.org.uk/family-court-reporting-watch-roundup-january-2025/)** | **2025-02-07** | Jan: 3 judgments, pre-PD12R baseline | **Y** | Baseline for transparency | • **Only 3 judgments** in Jan — **pre-PD12R low**<br>• **All anonymised** — no transparency orders<br>• **Keywords**: pre-transparency, publication drought, judicial culture |
| 27 | [sara-sharif-judges...](https://transparencyproject.org.uk/identification-of-judges-in-sara-sharif-family-court-history/) | 2025-01-02 | Judge naming in Sara Sharif. | **Y** | Judge ID policy. | • **Judges named** in high-profile case history<br>• **Public interest override**<br>• **Keywords**: judge identification, Sara Sharif, public interest |
| 28 | [new-court-rules...](https://transparencyproject.org.uk/new-court-rules-allow-more-reporting-from-family-courts/) | 2024-12-20 | PD12R launch. | **Y** | New law. | • **PD12R = legal revolution**: reporters in court<br>• **Transparency orders standard**<br>• **Keywords**: PD12R, reporting pilot end, open justice |
| 29 | [injuries-to-a-baby-part-2...](https://transparencyproject.org.uk/injuries-to-a-baby-part-2-the-courts-decisions/) | 2025-04-02 | Baby injury Part 2. | **N** | Case outcome. | — |
| 30 | [injuries-to-a-baby-part-1...](https://transparencyproject.org.uk/injuries-to-a-baby-part-1-a-mystery-to-be-solved-by-the-family-court/) | 2025-04-01 | Baby injury Part 1. | **N** | Case puzzle. | — |
| 31 | [presumption-review...](https://transparencyproject.org.uk/the-review-of-the-presumption-of-parental-involvement-latest-news/) | 2025-04-22 | PPI review update. | **N** | Policy. | — |
| 32 | [pr-about-pr](https://transparencyproject.org.uk/pr-about-pr/) | 2025-04-04 | Media & PR commentary. | **N** | Meta. | — |
| 33 | [intermediaries-guidance...](https://transparencyproject.org.uk/new-practice-guidance-on-intermediaries-in-family-courts/) | 2025-05-13 | Intermediaries guidance. | **N** | Fair trial. | — |
| 34 | [judges-names-coa...](https://transparencyproject.org.uk/court-of-appeal-says-judges-names-should-not-be-anonymised/) | 2025-03-16 | CoA: no judge anonymity. | **Y** | Landmark. | • **CoA ruling**: judge names **should be public**<br>• **Anonymity = exceptional**<br>• **Keywords**: judge anonymity, open justice, accountability |
| **35** | **[family-court-reporting-watch-roundup-73](https://transparencyproject.org.uk/family-court-reporting-watch-roundup-73/)** | **2025-03-06** | #73: 6 judgments, judge naming debate | **Y** | Trend: judge anonymity under scrutiny | • **6 judgments** — **volume rising**<br>• **Judge naming debate begins** post-CoA<br>• **Keywords**: judge naming, publication increase, transparency momentum |
| 36 | [anonymous-judge-coa...](https://transparencyproject.org.uk/court-of-appeal-to-consider-the-idea-of-the-anonymous-judge/) | 2025-02-17 | CoA to review anon judges. | **Y** | Pending ruling. | • **CoA to rule** on anonymous judge concept<br>• **Tension**: safety vs. accountability<br>• **Keywords**: anonymous judge, judicial safety, open justice |
| 37 | [pilot-to-pd12r...](https://transparencyproject.org.uk/one-small-step-at-a-time-from-pilot-to-practice-direction/) | 2024-12-20 | Pilot → PD12R. | **Y** | Historical shift. | • **Reporting pilot → permanent law**<br>• **From 4 courts to nationwide**<br>• **Keywords**: transparency pilot, PD12R, systemic change |
| 38 | [court-delays...](https://transparencyproject.org.uk/updates-on-the-operation-of-family-courts-mainly-about-delay/) | 2024-12-13 | Court delays. | **N** | Operations. | — |
| 39 | [repealing-presumption...](https://transparencyproject.org.uk/repealing-the-presumption-an-explainer/) | 2025-04-28 | PPI repeal explainer. | **N** | Substantive law. | — |
| 40 | [29974-2](https://transparencyproject.org.uk/29974-2/) | 2025-04-24 | Chronic neglect CMH. | **N** | Case. | — |
| 41 | [government-outcome...](https://transparencyproject.org.uk/government-announces-outcome-of-the-review-into-the-family-court-presumption-of-involvement-of-both-parents-in-a-childs-life/) | 2025-04-22 | PPI review outcome. | **N** | Policy. | — |
| 42 | [domestic-abuse-research...](https://transparencyproject.org.uk/new-research-shows-domestic-abuse-issues-fall-by-the-wayside-in-making-decisions-about-children/) | 2025-04-16 | DA sidelined. | **N** | Research. | — |
| 43 | [gatekeeping-consultation...](https://transparencyproject.org.uk/consultation-on-allocation-and-gatekeeping-in-family-courts/) | 2025-10-11 | Gatekeeping for reporters. | **Y** | Access rule. | • **Listing transparency** = key to reporter access<br>• **Gatekeeping teams** must publish hearings<br>• **Keywords**: court lists, gatekeeping, reporter access |
| 44 | [no-contact-order...](https://transparencyproject.org.uk/an-order-for-no-contact-at-west-london-family-court/) | 2025-10-10 | No-contact order. | **N** | Case. | — |
| **45** | **[family-court-reporting-watch-roundup-august-sept-2025](https://transparencyproject.org.uk/family-court-reporting-watch-roundup-august-sept-2025/)** | **2025-10-03** | Aug–Sep: 8 judgments, transparency orders standard | **Y** | Maturity: PD12R embedded | • **8 judgments** — **highest yet**<br>• **Transparency orders now routine**<br>• **Keywords**: normalization, PD12R maturity, reporting culture shift |
| 46 | [judgment-in-welsh](https://transparencyproject.org.uk/judgment-given-and-published-in-welsh/) | 2025-09-30 | Welsh judgment. | **Y** | Bilingual access. | • **First Welsh-language judgment** on TNA<br>• **Bilingual transparency** begins<br>• **Keywords**: Welsh language, accessibility, regional justice |
| 47 | [reporter-attendance-guidance](https://transparencyproject.org.uk/updated-guidance-what-to-do-when-a-reporter-attends-your-hearing/) | 2025-09- fictional | Updated reporter protocol. | **Y** | Official guidance. | • **Updated PD12R guidance**: what to do when reporter arrives<br>• **Standard script** for judges<br>• **Keywords**: reporter protocol, judicial training, PD12R |
| 48 | [will-my-judgment-be-published](https://transparencyproject.org.uk/will-my-family-court-judgment-be-published/) | 2025-09-19 | Publication explainer. | **Y** | Public FAQ. | • **Publication criteria**: seriousness, public interest<br>• **Not automatic** — judge decides<br>• **Keywords**: publication threshold, litigant FAQ |
| 49 | [wardship-somalia...](https://transparencyproject.org.uk/british-teenager-becomes-a-ward-of-court-to-escape-from-somalia/) | 2025-06-25 | Wardship abroad. | **N** | Case. | — |
| 50 | [cardiff-happy-ending...](https://transparencyproject.org.uk/a-happy-ending-in-cardiff-family-court/) | 2025-06-18 | Positive outcome. | **N** | Case. | — |
| 51 | [foster-shortage...](https://transparencyproject.org.uk/children-left-with-harmful-parents-because-of-lack-of-foster-carers/) | 2025-06-12 | Foster crisis. | **N** | Systemic. | — |
| 52 | [mother-prison-contempt...](https://transparencyproject.org.uk/sending-a-mother-to-prison-for-contempt-of-court/) | 2025-06-10 | Contempt committal. | **N** | Sanction. | — |
| **53** | **[family-court-reporting-watch-roundup-july-2025](https://transparencyproject.org.uk/family-court-reporting-watch-roundup-july-2025/)** | **2025-07-31** | July: 6 judgments, first bilingual reporting | **Y** | Innovation: Welsh reporting | • **6 judgments** — **steady growth**<br>• **First Welsh reporting** noted<br>• **Keywords**: bilingual reporting, regional variation |
| 54 | [ghana-appeal...](https://transparencyproject.org.uk/14-year-old-boy-taken-to-ghana-appeal-judgment/) | 2025-07-25 | Ghana removal appeal. | **N** | Jurisdiction. | — |
| 55 | [adoption-placement...](https://transparencyproject.org.uk/legal-blogging-placement-order-for-adoption-of-a-baby/) | 2025-07-18 | Adoption order. | **N** | Case. | — |
| 56 | [failed-reunification...](https://transparencyproject.org.uk/a-failed-reunification-plan/) | 2025-07-11 | Reunification fails. | **N** | Case. | — |
| **57** | **[family-court-reporting-watch-roundup-june-2025](https://transparencyproject.org.uk/family-court-reporting-watch-roundup-june-2025/)** | **2025-06-30** | June: 7 judgments, parent speech cases rise | **Y** | Trend: parental voice | • **7 judgments** — **peak so far**<br>• **Parent speech cases increase** under transparency orders<br>• **Keywords**: parental narrative, transparency order impact |
| 58 | [boys-with-dad...](https://transparencyproject.org.uk/if-i-had-to-live-with-mum-id-jump-out-of-the-window-why-two-boys-ended-up-living-with-their-dad/) | 2025-06-05 | Boys choose dad. | **N** | Case. | — |
| 59 | [legal-blogging-new-phase](https://transparencyproject.org.uk/legal-blogging-in-the-family-court-a-new-phase/) | 2023-01-01 | Legal blogging launch. | **Y** | Origin story. | • **Legal blogging launched** — new transparency tool<br>• **Training + pilot** = foundation of change<br>• **Keywords**: legal blogging, transparency pilot, origin |
| 60 | [future-open-justice...](https://transparencyproject.org.uk/whats-the-future-for-open-justice-and-justice-system-data-policy/) | 2023-02-24 | Open justice vision. | **Y** | Long-term agenda. | • **Vision**: data dashboards, full publication, judge naming<br>• **Open justice = democracy**<br>• **Keywords**: data policy, future transparency, systemic reform |
